//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TheTower
{
    public class Switch : Structure
    {
        public Switch(int id, Trap trap) : base("A switch", id)
        {
            this.Target = trap;
        }
        public Trap Target { get; private set; }

        public override Actor clone()
        {
            return this;
        }

    }
}