//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TheTower
{
    /**
     * Lucas Salom
     * Trap Subclass - Explosive
     * No Collision
     * Explodes upon being touched
     */
    public class TrapExplosive : Trap
    {
        public TrapExplosive(string name, int id)
            : base(name, id, 20)
        {
            //Base Stats
            //20 Power
            this.Action = new TrapExplode(this);
        }
    }
}
