//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Windows.Forms;

namespace TheTower
{
    // ADD IN IMAGE ( Preferably PNG), DRAW METHOD
    // public void draw( PaintEventArgs e, int x, int y)
    // {
    //  e.Graphics.DrawImage(this.image,x,y,width,height);
    // }
    // ALSO ADD IN A COMPLETE WALL AND FLOOR CLASS FOR USE IN TESTING
    public abstract class Actor : Drawable
    {
        #region Member Variables and Ctor
        public string Name { get; private set; }
        protected Image Img;
        protected List<string> Tags;
        protected Tile CurTile;
        protected int ID;

        public Actor(string name, int ID)
        {
            this.ID = ID;
            this.Name = name;
            this.CurTile = null;
            this.Tags = new List<string>();
            this.Tags.Add("Drawable");
            this.Img = null;
        }
        #endregion

        #region Overriden Object Methods

        /**
         *  Gets a shallow copy of the actor(same image data)
         * */
        public abstract Actor clone();
        public override bool Equals(object obj)
        {
            if (obj is Actor)
                return this.ID == ((Actor)obj).ID;
            return false;
        }
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
        public override string ToString()
        {
            return this.Name;
        }
        #endregion

        #region Getters
        public void AddTag(string tag)
        {
            this.Tags.Add(tag);
        }
        public void SetTile(Tile t)
        {
            this.CurTile = t;
        }
        public Tile GetTile()
        {
            return this.CurTile;
        }
        public List<string> GetTags()
        {
            return this.Tags;
        }
        public bool hasTag(String s)
        {
            bool ret = false;
            foreach (String tag in this.Tags)
            {
                if (tag.Equals(s))
                    ret = true;
            }
            return ret;
        }
        /**
         * Gets the image for the actor
         * @author Jakob Wilson
         * */
        public Image getImage()
        {
            return this.Img;
        }
#endregion

        #region Setters
        /**
         * Sets the image for the actor
         * @author Jakob Wilson
         * */
        public void setImage(Image img)
        {
            this.Img = img;
        }

        #endregion

        #region Draw
        public virtual void Draw(PaintEventArgs e, int x, int y)
        {
            if (this.Img != null)
                e.Graphics.DrawImage(this.Img, x, y, this.Img.Width, this.Img.Height);
        }
        #endregion
    }
}

