//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TheTower
{
    public class TrapExplosive : Trap
    {
        public TrapExplosive(int id)
            : base("An explosive trap", id, 20)
        {
            //Base Stats
            //20 Power
        }
    }
}
