//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TheTower
{
    public class Trap : Structure
    {
        public Trap(string name, int id, int power)
            : base(name, id)
        {
            this.Power = power;
        }
        public int Power { get; private set; }
        public int GetPower()
        {
            return this.Power;
        }
    }
}