//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TheTower
{
    public class Wall : Structure
    {
        public Wall(string name, int id)
            : base(name, id)
        {
            this.AddTag("Collidable");
            this.AddTag("Wall");
        }
        public override Actor clone()
        {
            Actor ret = new Wall(this.Name, this.ID);
            ret.setImage(this.Img);
            return ret;
        }
    }
}